[tool.poetry]
name = "poetry"
version = "0.1.0"
description = ""
authors = ["yultami <yuliacarti@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
punq = "^0.7.0"
pytest = "^8.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
